CHUNK_MIN_CHARS = 400
CHUNK_MAX_CHARS = 900
EMBED_MODEL = "all-MiniLM-L6-v2"
EMBED_DIMS = 384
DB_NAME = "engram"
VECTOR_INDEX = "chunk_vec"
DEFAULT_USER = "demo_user"
VECTOR_INDEX_READY_TIMEOUT_S = 120
