CHUNK_MIN_CHARS = 400
CHUNK_MAX_CHARS = 900
EMBED_MODEL = "all-MiniLM-L6-v2"
EMBED_DIMS = 384
DB_NAME = "engram"
VECTOR_INDEX = "chunk_vec"
DEFAULT_USER = "demo_user"
VECTOR_INDEX_READY_TIMEOUT_S = 120

KAPPA = 1.5
HALF_LIFE_H = 72.0
MIN_WINDOWS = 3
DWELL_S = 4.0
ARTIFACT_UV = 150.0

RECALL_GROW_S = 0.7
HALF_LIFE_GROW_BASE = 1.3
HALF_LIFE_GROW_WEIGHT = 0.7
RECALL_SHRINK_S = 0.4
HALF_LIFE_MIN_H = 24.0
HALF_LIFE_SHRINK = 0.6
SELECT_K = 5
